---

jenkins_connection_delay: 5
jenkins_connection_retries: 10
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 9090
jenkins_url:  "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
jenkins_jar_location: /var/lib/jenkins/
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_plugin_updates_expiration: 86400
jenkins_admin_username: admin
jenkins_admin_password: admin
app_user: jenkins
key: jenkins-ci.org.key
url: http://pkg.jenkins-ci.org
deb: debian-stable
redhat: redhat-stable
jenkins_url_prefix: " "
jenkins_apt_key_deb: "{{ url }}/{{deb}}/{{ key }}"
jenkins_apt_key_redhat: "{{ url }}/{{redhat}}/{{ key }}"
jenkins_apt_key_id_deb: D50582E6
jenkins_apt_repository_deb: deb http://pkg.jenkins-ci.org/debian-stable binary/
jenkins_init_file: /etc/sysconfig/jenkins

dependencies_deb:
  
  - 'curl'
  - 'ca-certificates'
  - 'apt-transport-https'
dependencies_se:
  
  - 'curl'
  - 'libselinux-python'
  - 'initscripts'
  
plugins:
  - 'git'
  - 'workflow-aggregator'
  - 'copyartifact'
  - 'rebuild'
  - 'docker'
  - 'maven'
  - 'gradle'
  - 'ansible'
  - 'javadoc'
  - 'junit'
  - 'thinbackup'
  
  
  
  

